#!/usr/bin/env bash
# SFS 에이전트 행동 가드레일이 런타임 컨텍스트와 어댑터에 남아 있는지 검증한다.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_contains() {
  local file="$1"
  local needle="$2"
  local label="$3"

  [[ -f "${file}" ]] || fail "${label}: missing file ${file}"
  grep -Fq -- "${needle}" "${file}" || fail "${label}: missing '${needle}'"
}

assert_not_contains() {
  local file="$1"
  local needle="$2"
  local label="$3"

  [[ -f "${file}" ]] || fail "${label}: missing file ${file}"
  if grep -Fq -- "${needle}" "${file}"; then
    fail "${label}: unexpected '${needle}'"
  fi
}

kernel="${DIST_DIR}/templates/.sfs-local-template/context/kernel.md"
brainstorm="${DIST_DIR}/templates/.sfs-local-template/context/commands/brainstorm.md"
plan="${DIST_DIR}/templates/.sfs-local-template/context/commands/plan.md"
implement="${DIST_DIR}/templates/.sfs-local-template/context/commands/implement.md"
loop="${DIST_DIR}/templates/.sfs-local-template/context/commands/loop.md"
review="${DIST_DIR}/templates/.sfs-local-template/context/commands/review.md"
tidy="${DIST_DIR}/templates/.sfs-local-template/context/commands/tidy.md"
plan_template="${DIST_DIR}/templates/.sfs-local-template/sprint-templates/plan.md"
review_script="${DIST_DIR}/templates/.sfs-local-template/scripts/sfs-review.sh"
common_script="${DIST_DIR}/templates/.sfs-local-template/scripts/sfs-common.sh"
auth_script="${DIST_DIR}/templates/.sfs-local-template/scripts/sfs-auth.sh"
commit_script="${DIST_DIR}/templates/.sfs-local-template/scripts/sfs-commit.sh"
model_profiles="${DIST_DIR}/templates/.sfs-local-template/model-profiles.yaml"
researcher="${DIST_DIR}/templates/.sfs-local-template/personas/researcher.md"
cpo="${DIST_DIR}/templates/.sfs-local-template/personas/cpo-evaluator.md"
installer="${DIST_DIR}/install.sh"
upgrader="${DIST_DIR}/upgrade.sh"
claude_template="${DIST_DIR}/templates/CLAUDE.md.template"
agents_template="${DIST_DIR}/templates/AGENTS.md.template"
gemini_template="${DIST_DIR}/templates/GEMINI.md.template"
sfs_template="${DIST_DIR}/templates/SFS.md.template"
codex_skill_template="${DIST_DIR}/templates/codex-skill/SKILL.md"
plugin_command="${DIST_DIR}/plugins/solon/commands/sfs.md"
plugin_readme="${DIST_DIR}/plugins/solon/README.md"

assert_contains "${kernel}" "surface material assumptions" "kernel assumptions"
assert_contains "${kernel}" "minimum useful slice" "kernel simplicity"
assert_contains "${kernel}" "Read actual files, command output, and error logs" "kernel evidence"
assert_contains "${kernel}" "Executable Action Ownership is ambient" "kernel executable action ownership"
assert_contains "${kernel}" "Do not hand the user copy-paste commands" "kernel no runnable copy-paste handoff"
assert_contains "${kernel}" "Distinguish true blockers from approval gates" "kernel blocker approval split"
assert_contains "${kernel}" "session-scoped authorization" "kernel session authorization"
assert_contains "${kernel}" "Shell state is not a user problem" "kernel shell state ownership"
assert_contains "${kernel}" "Monitor checkpoint classification is mandatory" "kernel monitor classification"
assert_contains "${kernel}" "commit delta, PR/head delta, local dirty state" "kernel monitor evidence fields"
assert_contains "${kernel}" "lane-utilization evidence or waiver" "kernel monitor lane evidence"
assert_contains "${kernel}" "request-response probe, never process/auth-status alone" "kernel monitor probe liveness"
assert_contains "${kernel}" "Probes use a static" "kernel monitor static probe"
assert_contains "${kernel}" "benign payload only" "kernel monitor benign probe"
assert_contains "${kernel}" "status/category/timestamp/redacted error class" "kernel monitor redacted evidence"
assert_contains "${kernel}" "do not persist raw" "kernel monitor no raw persistence"
assert_contains "${kernel}" "stdout/stderr, bearer/auth tokens, env vars, prompt bodies, model responses" "kernel monitor no sensitive evidence"
assert_contains "${kernel}" "heartbeat/automation cleanup and durable wiki/report evidence" "kernel monitor close evidence"
assert_contains "${kernel}" "do not end Korean sentences with a closing colon" "kernel Korean output"
assert_contains "${kernel}" "current SFS workbench artifacts" "kernel SFS notes"
assert_contains "${kernel}" "Multi-agent work is thin supervision" "kernel thin supervision"
assert_contains "${kernel}" "Compactness is never a pass condition" "kernel compact quality floor"
assert_contains "${kernel}" "verification results stay intact" "kernel compact evidence retention"
assert_contains "${kernel}" "Decision questions must be self-contained" "kernel decision clarity"
assert_contains "${kernel}" "question/recommendation-only table" "kernel no recommendation-only choice table"
assert_contains "${kernel}" "show every viable option" "kernel all options visible"
assert_contains "${kernel}" "ask one decision at a time" "kernel sequential decision fallback"
assert_contains "${kernel}" "compact option bundle" "kernel no compact option bundle"
assert_contains "${kernel}" "권장안 그대로 확정" "kernel natural confirmation phrase"
assert_contains "${kernel}" "Gate order is a runtime contract" "kernel gate order"
assert_contains "${kernel}" "Review verdicts are success criteria, not effort counters" "kernel review verdict"
assert_contains "${kernel}" "Same-cycle micro-rework is autopilot" "kernel same-cycle micro rework"
assert_contains "${kernel}" "user to request the next review" "kernel no user-triggered rerun"
assert_contains "${kernel}" "self-CPO/cross review" "kernel autopilot review loop"
assert_contains "${kernel}" 'not ask "진행?"' "kernel no generic proceed ask"
assert_contains "${kernel}" "User-call minimalism is mandatory" "kernel user-call minimalism"
assert_contains "${kernel}" "User-escalation premise guard is mandatory" "kernel premise guard"
assert_contains "${kernel}" "Cross-review findings are" "kernel cross finding triage"
assert_contains "${kernel}" "already answered" "kernel answered finding no escalation"
assert_contains "${kernel}" "reject delete while" "kernel delete dependents default"
assert_contains "${kernel}" "new product judgment" "kernel product judgment boundary"
assert_contains "${kernel}" "SFS commit guidance must use the SFS command surface" "kernel sfs commit surface"
assert_contains "${kernel}" "commits and pushes the current branch by default" "kernel sfs commit pushes"
assert_contains "${kernel}" 'host-local `/commit` skill' "kernel no host-local commit skill"
assert_contains "${kernel}" "Advisor review is not a self-CPO PASS" "kernel advisor not self CPO"
assert_contains "${kernel}" "Missing self-CPO evidence is partial" "kernel self CPO missing partial"
assert_contains "${kernel}" "Cross review comes after local self-review passes" "kernel self before cross"
assert_contains "${kernel}" "recorded self-CPO fallback PASS" "kernel self CPO fallback"
assert_contains "${kernel}" "bare self-CPO PASS still blocks implementation" "kernel bare self CPO blocks"
assert_contains "${kernel}" "Role split is invariant" "kernel role split"
assert_contains "${kernel}" "Claude coding-capable" "kernel claude coding lane"
assert_contains "${kernel}" "Sonnet 4.6" "kernel claude sonnet 4.6"
assert_contains "${kernel}" "Haiku is non-coding helper-only" "kernel haiku non-coding"
assert_contains "${kernel}" "Substantive research should prefer" "kernel gemini research preference"
assert_contains "${kernel}" "Gemini 3 Pro auto" "kernel gemini research model"
assert_contains "${kernel}" 'Gemini uses `gemini-3-pro-auto` for every SFS role' "kernel gemini all roles"
assert_contains "${kernel}" 'general worker/generator slices use `gpt-5.4`' "kernel codex worker default"
assert_contains "${kernel}" 'bounded repo-aware coding helpers use' "kernel codex coding helper"
assert_contains "${kernel}" 'judgment-free mechanical implementation helpers use' "kernel codex spark boundary"
assert_contains "${kernel}" "self-agent top-model CPO review" "kernel top-model self CPO"
assert_contains "${kernel}" "Claude self-CPO uses Opus 4.7" "kernel claude self CPO model"
assert_contains "${kernel}" "Codex self-CPO uses" "kernel codex self CPO"
assert_contains "${kernel}" "xhigh reasoning" "kernel codex self CPO xhigh"
assert_contains "${kernel}" 'Gemini self-CPO uses `gemini-3-pro-auto`' "kernel gemini self CPO"
assert_contains "${kernel}" "same self-CPO loop repeats" "kernel self CPO repeats"
assert_contains "${kernel}" "until PASS" "kernel self CPO until pass"
assert_contains "${kernel}" "Taxonomy is a product function" "kernel taxonomy function"
assert_contains "${kernel}" "one plain-language question" "kernel missing arg question"
assert_contains "${kernel}" 'Other` or `Type something`' "kernel placeholder labels"
assert_contains "${kernel}" "이번 sprint 목표를 한 줄로 말해 주세요" "kernel Korean start question"

assert_contains "${brainstorm}" "docs/solon/domain-map.md" "brainstorm domain map"
assert_contains "${brainstorm}" "read-only researcher" "brainstorm researcher"
assert_contains "${brainstorm}" "A/A/A/C/C 확정" "brainstorm no compact bundle confirmation"
assert_contains "${brainstorm}" "권장안 다시 보여줘" "brainstorm recommendation replay guard"

assert_contains "${plan}" "explicit non-goals" "plan tradeoffs"
assert_contains "${plan}" "verify by ..." "plan verification"
assert_contains "${plan}" "mandatory" "plan no root notes"
assert_contains "${plan}" "root-level" "plan no root notes"
assert_contains "${plan}" "sfs review --gate 3" "plan pre-implementation review"
assert_contains "${plan}" "Gate 3 plan review is mandatory before implementation" "plan mandatory review"
assert_contains "${plan}" 'Do not offer `sfs implement`, worker delegation, or model-selection choices' "plan no direct implement action rail"
assert_contains "${plan}" "plan until PASS first, then run cross review" "plan self before cross"
assert_contains "${plan}" "deterministic and inside" "plan same-cycle micro rework"
assert_contains "${plan}" "autopilot the micro-fix" "plan autopilot micro rework"
assert_contains "${plan}" 'Do not ask "진행?"' "plan no generic proceed ask"
assert_contains "${plan}" "brainstorm + plan review" "plan user-call minimalism"
assert_contains "${plan}" "Escalate only when" "plan user escalation boundary"
assert_contains "${plan}" "Before escalating a self/cross-review finding as a user question" "plan premise guard"
assert_contains "${plan}" "says the entity is metadata-only" "plan metadata ownership guard"
assert_contains "${plan}" "reject delete while dependents exist" "plan delete dependents default"
assert_contains "${plan}" "self-CPO mini-check, not only advisor consultation" "plan self CPO not advisor"
assert_contains "${plan}" "SEED, placeholder, mock, or fallback" "plan seed placeholder non acceptance"
assert_contains "${plan}" "Do not use review volume as a stopping rule" "plan no review volume stop"
assert_contains "${plan}" "C-Level owns the contract" "plan C-Level boundary"
assert_contains "${plan}" 'use `gpt-5.4` for the normal implementation worker' "plan codex worker default"
assert_contains "${plan}" '`gpt-5.3-codex` for' "plan codex coding helper"
assert_contains "${plan}" 'code-design judgment remains' "plan codex spark boundary"
assert_contains "${plan}" "docs/solon/domain-map.md" "plan domain map"
assert_contains "${plan}" "do not end with" "plan decision clarity"
assert_contains "${plan}" 'unexplained `Q1`' "plan unexplained Q1 guardrail"
assert_contains "${plan}" "Never show only the recommended column" "plan no recommendation-only choices"
assert_contains "${plan}" 'Define labels such as `A/B/C/D` inline' "plan option label definitions"
assert_contains "${plan}" "ask the decisions sequentially" "plan sequential choices"
assert_contains "${plan}" "compact bundle confirmations" "plan no compact bundle confirmation"
assert_contains "${plan}" "권장안 다시 보여줘" "plan recommendation replay guard"
assert_contains "${plan}" "avoid translationese" "plan no translationese review readiness"
assert_contains "${plan}" "files/artifacts are mapped per slice" "plan review readiness slice mapping"

assert_contains "${plan_template}" "Gate 2 결정이 요구사항과 AC에 연결되어 있다" "plan template Gate 2 decision mapping"
assert_contains "${plan_template}" "slice별 파일/산출물 매핑이 있다" "plan template slice artifact mapping"
assert_contains "${plan_template}" 'Codex 일반 worker는 `gpt-5.4`' "plan template Codex worker"
assert_contains "${plan_template}" 'bounded coding helper는 `gpt-5.3-codex`' "plan template Codex coding helper"
assert_contains "${plan_template}" "무판단 기계적 구현 보조 작업에만 쓴다" "plan template Spark boundary"
assert_not_contains "${plan_template}" "열린 결정이 이름 붙어 있다" "plan template no awkward open-decision wording"

assert_contains "${implement}" "Keep changes surgical" "implement surgical changes"
assert_contains "${implement}" "speculative flexibility" "implement simplicity"
assert_contains "${implement}" "dirty" "implement worktree respect"
assert_contains "${implement}" "worktree changes" "implement worktree respect"
assert_contains "${implement}" "full error/log output" "implement read errors"
assert_contains "${implement}" "smallest relevant test" "implement verification"
assert_contains "${implement}" "Execute approved runnable steps yourself" "implement executable action ownership"
assert_contains "${implement}" "approval gates and true blockers differently" "implement blocker approval split"
assert_contains "${implement}" "session authorization" "implement session authorization"
assert_contains "${implement}" "secrets or production-write flows" "implement prod secrets execution"
assert_contains "${implement}" "Do not ask the user to export variables" "implement no shell-state delegation"
assert_contains "${implement}" ".sfs-local/personas/researcher.md" "implement researcher"
assert_contains "${implement}" "files_scope explicit and disjoint" "implement worker scope"
assert_contains "${implement}" "requires a Gate 3 Plan review PASS" "implement preflight review"
assert_contains "${implement}" "default implementation owner is the worker/generator model" "implement worker model default"
assert_contains "${implement}" 'normal implementation worker is `gpt-5.4`' "implement codex worker default"
assert_contains "${implement}" '`gpt-5.3-codex` for bounded repo-aware coding helper work' "implement codex coding helper"
assert_contains "${implement}" '`gpt-5.3-codex-spark` only for judgment-free mechanical implementation' "implement codex spark boundary"
assert_contains "${implement}" "worker/helper lanes use Sonnet 4.6" "implement claude sonnet coding lane"
assert_contains "${implement}" "Haiku must not write" "implement haiku no code"
assert_contains "${implement}" 'Gemini uses `gemini-3-pro-auto` for every SFS role' "implement gemini all roles"
assert_contains "${implement}" "Self-review must pass first; cross review follows" "implement self before cross"
assert_contains "${implement}" "recorded self-CPO fallback evidence" "implement self CPO fallback"
assert_contains "${implement}" "Agent mode is an implementation-time choice" "implement agent mode choice"
assert_contains "${implement}" "Default to single-agent" "implement single default"
assert_contains "${implement}" "--agent-mode parallel --agents codex,claude[,gemini]" "implement parallel option"
assert_contains "${implement}" "one-sentence proposed commit" "implement commit unit guard"
assert_contains "${implement}" "native/workspace language" "implement native commit language"
assert_contains "${implement}" "After any implementation" "implement post review required"
assert_contains "${implement}" "self-agent top-model CPO review" "implement self-agent top-model CPO"
assert_contains "${implement}" "Opus 4.7" "implement claude self CPO model"
assert_contains "${implement}" '`gpt-5.5` with xhigh reasoning' "implement codex self CPO model"
assert_contains "${implement}" 'Gemini routes it to `gemini-3-pro-auto`' "implement gemini self CPO model"
assert_contains "${implement}" "repeat self-CPO until PASS" "implement self CPO repeat"
assert_contains "${implement}" "cross review between agents is required" "implement parallel cross review"

assert_contains "${review}" "Review actual diff, files, test output, and logs" "review evidence"
assert_contains "${review}" "Gate 3 plan review is the required bridge between plan and implement" "review plan-to-implement bridge"
assert_contains "${review}" "Gate 3 review has a sequence: local self-review until PASS" "review self before cross"
assert_contains "${review}" "Gate 3 may use self-CPO fallback" "review self CPO fallback"
assert_contains "${review}" "Local self-review means a self-CPO mini-check" "review self CPO meaning"
assert_contains "${review}" "If that evidence is absent, return partial" "review self CPO missing partial"
assert_contains "${review}" "deterministic, narrow findings" "review same-cycle micro rework"
assert_contains "${review}" "autopilot" "review autopilot micro rework"
assert_contains "${review}" 'do not ask "진행?"' "review no generic proceed ask"
assert_contains "${review}" "User-call minimalism" "review user-call minimalism"
assert_contains "${review}" "User-escalation premise guard" "review premise guard"
assert_contains "${review}" "reviewer frame is valid" "review reviewer frame validation"
assert_contains "${review}" "reject delete while dependents exist" "review delete dependents default"
assert_contains "${review}" "Escalate instead of auto-reworking" "review user escalation boundary"
assert_contains "${loop}" 'must state `progressing`, `slow`' "loop monitor state vocabulary start"
assert_contains "${loop}" '`stalled`, `dead`, or `auth_blocked`' "loop monitor state vocabulary end"
assert_contains "${loop}" "record commit delta, PR/head delta" "loop monitor evidence fields start"
assert_contains "${loop}" "local dirty state, test/check delta" "loop monitor evidence fields end"
assert_contains "${loop}" "lane-utilization evidence or waiver" "loop monitor lane evidence"
assert_contains "${loop}" 'next action `wait`' "loop monitor next action"
assert_contains "${loop}" '`probe`, `revive`, or `close`' "loop monitor next action values"
assert_contains "${loop}" "request-response probe, never" "loop monitor request-response liveness"
assert_contains "${loop}" "process/auth-status alone" "loop monitor no process-only liveness"
assert_contains "${loop}" "static benign payload" "loop monitor static probe"
assert_contains "${loop}" "Use a static benign payload only, never" "loop monitor static probe boundary"
assert_contains "${loop}" "workspace/user content, and persist only" "loop monitor no workspace content"
assert_contains "${loop}" "status/category/timestamp/redacted" "loop monitor redacted evidence"
assert_contains "${loop}" "raw stdout/stderr, bearer/auth tokens, env vars" "loop monitor no raw secrets"
assert_contains "${loop}" "prompt bodies, model responses, workspace/user content, or PII" "loop monitor no raw model/user data"
assert_contains "${loop}" "heartbeat/automation cleanup and durable" "loop monitor close evidence"
assert_contains "${review}" 'progressing`, `slow`, `stalled`, `dead`, or `auth_blocked`' "review monitor state vocabulary"
assert_contains "${review}" "commit delta, PR/head delta, local dirty state" "review monitor evidence fields"
assert_contains "${review}" "lane-utilization evidence or" "review monitor lane evidence"
assert_contains "${review}" "request-response probe, never process/auth-status alone" "review monitor liveness"
assert_contains "${review}" "static benign payload" "review monitor static probe"
assert_contains "${review}" "status/category/timestamp/redacted error class" "review monitor redacted evidence"
assert_contains "${review}" "Raw stdout/stderr" "review monitor no raw stdout"
assert_contains "${review}" "heartbeat/automation cleanup plus durable wiki/report evidence" "review monitor close evidence"
assert_contains "${review}" "Number of lenses, rounds, advisor" "review no volume pass"
assert_contains "${review}" "Flag overengineering" "review overengineering"
assert_contains "${review}" "Repeated review for the same sprint/gate must converge" "review lens convergence"
assert_contains "${review}" "later auto reviews reuse that" "review auto lens lock"
assert_contains "${review}" "exact verification command/result" "review verification evidence"
assert_contains "${review}" "self-validation risk" "review self-validation"
assert_contains "${review}" "self-agent" "review self-agent top-model CPO"
assert_contains "${review}" "Opus 4.7" "review claude self CPO model"
assert_contains "${review}" '`gpt-5.5` with xhigh reasoning' "review codex self CPO model"
assert_contains "${review}" 'Gemini self-CPO uses `gemini-3-pro-auto`' "review gemini self CPO model"
assert_contains "${review}" "repeats self-CPO until PASS" "review self CPO repeat"
assert_contains "${review}" "agent_mode: parallel" "review parallel mode"
assert_contains "${review}" "disjoint files_scope per lane" "review parallel scope"
assert_contains "${review}" "commit message per lane" "review parallel commit message"
assert_contains "${review}" "native/workspace language" "review native commit language"
assert_contains "${review}" "cross review" "review parallel cross review"
assert_contains "${review}" 'Pass names `sfs retro`' "review retro close path"
assert_contains "${tidy}" 'Do not recommend `report` before `retro`' "tidy no report-before-retro"
assert_contains "${review_script}" 'name `/sfs retro` as the normal close path' "review prompt retro close path"
assert_contains "${review_script}" "Advisor calls are not a self-CPO PASS" "review prompt advisor not self CPO"
assert_contains "${review_script}" "SFS_REVIEW_BRIDGE_PROBE_TIMEOUT_SEC" "review bridge probe timeout"
assert_contains "${review_script}" "preflight_review_executor_auth" "review auth preflight before prompt"
assert_contains "${review_script}" "Review was not started, and no CPO prompt was generated." "review auth preflight no prompt"
assert_contains "${review_script}" "CPO evaluator bridge probe failed before full review" "review bridge probe fail fast"
assert_contains "${review_script}" "SFS_REVIEW_BRIDGE_PROBE_OK" "review bridge probe marker"
assert_contains "${review_script}" "latest commit reviewable file manifest" "review latest commit evidence manifest"
assert_contains "${review_script}" "current sprint shared handoff evidence manifest" "review shared handoff evidence manifest"
assert_contains "${review_script}" "first-class review target; full file included" "review full small first-class evidence"
assert_contains "${review_script}" "SFS_REVIEW_DIR_EXPANSION_MAX" "review bounded directory expansion"
assert_contains "${review_script}" "INDEXED_REVIEW_EVIDENCE_PATHS_CACHE" "review cached indexed evidence paths"
assert_contains "${review_script}" 'update_frontmatter "${REVIEW_PATH}" "goal"' "review goal refresh"
assert_contains "${review_script}" 'update_frontmatter "${REVIEW_PATH}" "workspace"' "review workspace refresh"
assert_contains "${review_script}" 'claude -p "$(cat)"' "review claude prompt-argument bridge"
assert_not_contains "${review_script}" "claude -p --dangerously-skip-permissions" "review no stale claude dangerous stdin bridge"
assert_contains "${common_script}" 'eval "exec ${cmd}"' "common executor timeout kills real CLI"
assert_contains "${common_script}" "executor_interactive_tty_available" "common real tty preflight"
assert_contains "${common_script}" "SFS_REVIEW_<EXECUTOR>_CMD override; do not widen" "common eval allow-list comment"
assert_contains "${common_script}" 'claude -p "$(cat)"' "common claude prompt-argument bridge"
assert_not_contains "${common_script}" "claude -p --dangerously-skip-permissions" "common no stale claude dangerous stdin bridge"
assert_contains "${auth_script}" 'claude -p "$(cat)"' "auth probe claude prompt-argument bridge"
assert_contains "${auth_script}" "redact_auth_probe_artifact" "auth probe persisted artifact redaction"
assert_not_contains "${auth_script}" "claude -p --dangerously-skip-permissions" "auth probe no stale claude dangerous bridge"
assert_contains "${commit_script}" "and push the current branch by default" "commit script push default"
assert_contains "${commit_script}" "git push -u origin" "commit script upstream push"
assert_contains "${commit_script}" "--no-push only for local sandbox/release testing" "commit script no-push boundary"
assert_not_contains "${commit_script}" "This helper never runs git push" "commit script no stale push ban"
stale_report_cmd='/sfs report'
stale_retro_cmd='/sfs retro'
stale_close_phrase="usually \`${stale_report_cmd}\` then \`${stale_retro_cmd}\`"
assert_not_contains "${review_script}" "${stale_close_phrase}" "review prompt no stale report-then-retro"

assert_contains "${researcher}" "default_executor: gemini" "researcher default executor"
assert_contains "${researcher}" "Do not edit production files" "researcher read-only"
assert_contains "${researcher}" "docs/solon/domain-map.md" "researcher domain map"
assert_contains "${cpo}" "Advisor calls do not satisfy self-CPO" "cpo advisor not self CPO"
assert_contains "${cpo}" "lacks self-CPO evidence" "cpo missing self CPO partial"
assert_contains "${cpo}" "User-escalation premise" "cpo premise guard"
assert_contains "${cpo}" "reject-delete-with-dependents" "cpo delete dependents default"
assert_contains "${cpo}" "User-call minimalism" "cpo user-call minimalism"
assert_contains "${cpo}" "autopilot patch" "cpo autopilot patch"

assert_contains "${model_profiles}" "research_high" "model profiles research tier"
assert_contains "${model_profiles}" "intake_economy" "model profiles intake tier"
assert_contains "${model_profiles}" "facilitator_standard" "model profiles facilitator tier"
assert_contains "${model_profiles}" "default_applied" "model profiles default applied status"
assert_contains "${model_profiles}" "selected_policy=solon_recommended" "model profiles recommended default rule"
assert_contains "${model_profiles}" "researcher: research_high" "model profiles researcher policy"
assert_contains "${model_profiles}" ".sfs-local/personas/researcher.md" "model profiles researcher persona"
assert_contains "${model_profiles}" "role_boundaries" "model profiles role boundaries"
assert_contains "${model_profiles}" "self_cpo_check" "model profiles self CPO boundary"
assert_contains "${model_profiles}" "self-cpo-checker" "model profiles self CPO agent"
assert_contains "${model_profiles}" "Helper-grade simple I/O" "model profiles helper-grade advisor exemption"
assert_contains "${model_profiles}" "top-model strategic_high advisor" "model profiles top advisor rule"
assert_contains "${model_profiles}" "Advisor consultation is not self-CPO" "model profiles advisor not self CPO"
assert_contains "${model_profiles}" "Gate 3 Plan review must pass before worker/generator implementation starts" "model profiles gate invariant"
assert_contains "${model_profiles}" "Single-agent implementation is the default" "model profiles single default"
assert_contains "${model_profiles}" "Multi-agent implementation is opt-in" "model profiles parallel opt-in"
assert_contains "${model_profiles}" "AC/ADR subset ownership" "model profiles parallel AC/ADR"
assert_contains "${model_profiles}" "expected tests/evidence" "model profiles parallel evidence"
assert_contains "${model_profiles}" "output report path" "model profiles parallel report path"
assert_contains "${model_profiles}" "merge/conflict policy" "model profiles parallel merge policy"
assert_contains "${model_profiles}" 'model: "gpt-5.4-mini"' "model profiles codex intake model"
assert_contains "${model_profiles}" 'model: "gpt-5.4"' "model profiles codex facilitator model"
assert_contains "${model_profiles}" 'model: "gpt-5.3-codex"' "model profiles codex coding helper model"
assert_contains "${model_profiles}" 'model: "gpt-5.3-codex-spark"' "model profiles codex spark helper"
assert_contains "${model_profiles}" "coding-helper: code_helper" "model profiles coding helper policy"
assert_contains "${model_profiles}" "mechanical-implementation-helper: mechanical_implementation_economy" "model profiles mechanical helper policy"
assert_contains "${model_profiles}" 'model: "sonnet-4.6"' "model profiles claude sonnet 4.6"
assert_contains "${model_profiles}" 'model: "haiku"' "model profiles claude haiku helper"
assert_contains "${model_profiles}" "Haiku must not write code" "model profiles haiku no coding"
assert_contains "${model_profiles}" "Claude has no Haiku coding lane" "model profiles no haiku coding lane"
assert_contains "${model_profiles}" "Prefer the Gemini researcher executor" "model profiles gemini research preference"
assert_contains "${model_profiles}" 'model: "gemini-3-pro-auto"' "model profiles gemini 3 pro auto"
assert_contains "${model_profiles}" "Gemini uses Gemini 3 Pro auto for every SFS role" "model profiles gemini all roles"
assert_not_contains "${model_profiles}" "gemini-2.5" "model profiles no gemini 2.5 fallback"
assert_not_contains "${model_profiles}" "gemini-3.1-pro-preview" "model profiles no gemini 3.1 preview"
assert_not_contains "${model_profiles}" "gemini-3-flash-preview" "model profiles no gemini flash preview"
assert_contains "${model_profiles}" "implementation-worker and division-worker to gpt-5.4" "model profiles codex worker rule"
assert_contains "${model_profiles}" "bounded code helper work resolves to gpt-5.3-codex" "model profiles codex coding helper rule"
assert_contains "${model_profiles}" "judgment-free mechanical implementation helper work resolves to gpt-5.3-codex-spark" "model profiles codex spark rule"
assert_contains "${model_profiles}" "implementation-worker, division-worker, coding-helper, and mechanical-implementation-helper to sonnet-4.6" "model profiles claude worker/helper rule"
assert_contains "${model_profiles}" "Haiku is a non-coding helper tier only" "model profiles haiku non-coding only"
assert_contains "${model_profiles}" "gemini-3-pro-auto for every SFS role" "model profiles gemini every role rule"
assert_contains "${model_profiles}" "Do not use Gemini Flash or 2.5 fallback names" "model profiles no gemini flash fallback rule"
assert_contains "${review_script}" 'For Codex CPO/cross review, the requested review_high profile is gpt-5.5 with xhigh reasoning.' "review codex prompt review_high"
assert_contains "${review_script}" 'The default Codex shell bridge does not force model selection with CLI flags' "review codex prompt routing"
assert_contains "${review_script}" "User-escalation premise guard" "review prompt premise guard"
assert_contains "${review_script}" "reject-delete-with-dependents" "review prompt delete dependents default"
assert_contains "${review_script}" "User-call minimalism" "review prompt user-call minimalism"
assert_contains "${review_script}" "autopilot patch" "review prompt autopilot patch"
assert_contains "${review_script}" 'codex exec --full-auto --ephemeral --output-last-message \"${RUN_RESULT}\" -' "review codex prompt-based bridge"
assert_not_contains "${review_script}" 'SFS_REVIEW_CODEX_MODEL:-gpt-5.5' "review codex no default model cli flag"
assert_not_contains "${review_script}" 'SFS_REVIEW_CODEX_REASONING_EFFORT:-xhigh' "review codex no default reasoning cli flag"
assert_contains "${installer}" 'MODEL_POLICY="${SFS_MODEL_POLICY:-solon_recommended}"' "install recommended default"
assert_contains "${installer}" '[ "$MODEL_POLICY" != "solon_recommended" ]' "install preserves default-applied status"
assert_contains "${installer}" "agent model profile 기본값 적용" "install no prompt default"
assert_contains "${installer}" "Claude: advisor 는 Opus 4.7" "install claude top model"
assert_contains "${installer}" "worker/facilitator/code helper 는 Sonnet 4.6" "install claude sonnet worker"
assert_contains "${installer}" "Haiku 는 코딩 금지" "install haiku no coding"
assert_contains "${installer}" "gemini-3-pro-auto" "install gemini 3 pro auto"
assert_contains "${installer}" "Flash/2.5 fallback 은 쓰지 않습니다" "install no gemini flash 2.5 fallback"
assert_contains "${installer}" "advisor 호출은 self-CPO PASS 가 아닙니다" "install advisor not self CPO"
assert_contains "${installer}" "self-CPO mini-check" "install self CPO mini check"
assert_contains "${upgrader}" "MODEL_POLICY=\"solon_recommended\"" "upgrade recommended default"
assert_contains "${upgrader}" "solon_recommended 기본 role routing" "upgrade fallback migration"
assert_contains "${upgrader}" "Claude: advisor 는 Opus 4.7" "upgrade claude top model"
assert_contains "${upgrader}" "worker/facilitator/code helper 는 Sonnet 4.6" "upgrade claude sonnet worker"
assert_contains "${upgrader}" "Haiku 는 코딩 금지" "upgrade haiku no coding"
assert_contains "${upgrader}" "gemini-3-pro-auto" "upgrade gemini 3 pro auto"
assert_contains "${upgrader}" "Flash/2.5 fallback 은 쓰지 않습니다" "upgrade no gemini flash 2.5 fallback"
assert_contains "${upgrader}" "advisor 호출은 self-CPO PASS 가 아닙니다" "upgrade advisor not self CPO"
assert_contains "${upgrader}" "self-CPO mini-check" "upgrade self CPO mini check"

for handoff_doc in \
  "${claude_template}" \
  "${agents_template}" \
  "${gemini_template}" \
  "${sfs_template}" \
  "${codex_skill_template}" \
  "${plugin_command}" \
  "${plugin_readme}"
do
  assert_contains "${handoff_doc}" "docs/solon/<domain>/<subdomain>/<feature>/<yyyyMMdd>/" "domain handoff docs root path ${handoff_doc}"
  assert_contains "${handoff_doc}" "docs/solon/<english-workspace>/<yyyyMMdd>/" "legacy fallback handoff docs path ${handoff_doc}"
done
assert_not_contains "${claude_template}" "docs/<workspace>/<yyyyMMdd>/" "claude no stale root docs handoff"
assert_not_contains "${agents_template}" "docs/<workspace>/<yyyyMMdd>/" "agents no stale root docs handoff"
assert_not_contains "${gemini_template}" "docs/<workspace>/<yyyyMMdd>/" "gemini no stale root docs handoff"
assert_not_contains "${sfs_template}" "docs/<workspace>/<yyyyMMdd>/" "SFS no stale root docs handoff"
assert_contains "${sfs_template}" "compact option bundle" "SFS no compact option bundle"
assert_contains "${sfs_template}" "권장안 그대로 확정" "SFS natural confirmation phrase"
assert_contains "${sfs_template}" "Executable Action Ownership" "SFS executable action ownership"
assert_contains "${sfs_template}" "session-scoped authorization" "SFS session authorization"
assert_contains "${sfs_template}" "Shell state is agent-owned" "SFS shell state ownership"

adapter_files=(
  "${DIST_DIR}/templates/CLAUDE.md.template"
  "${DIST_DIR}/templates/AGENTS.md.template"
  "${DIST_DIR}/templates/GEMINI.md.template"
  "${DIST_DIR}/templates/codex-skill/SKILL.md"
  "${DIST_DIR}/templates/.agents/skills/sfs/SKILL.md"
  "${DIST_DIR}/templates/.claude/commands/sfs.md"
  "${DIST_DIR}/templates/.gemini/commands/sfs.toml"
  "${DIST_DIR}/templates/.codex/prompts/sfs.md"
  "${DIST_DIR}/commands/sfs.toml"
  "${DIST_DIR}/plugins/solon/commands/sfs.md"
)

for file in "${adapter_files[@]}"; do
  assert_contains "${file}" "surface material assumptions" "adapter guardrail ${file}"
  assert_contains "${file}" "report exact evidence" "adapter evidence ${file}"
  assert_contains "${file}" "배포해줘" "adapter Korean deploy trigger ${file}"
  assert_contains "${file}" "배포 프로세스 쭉 진행해줘" "adapter full release trigger ${file}"
  assert_contains "${file}" "review/검수" "adapter release review before done ${file}"
  assert_contains "${file}" "installed runtime verification" "adapter release installed runtime verification ${file}"
  assert_contains "${file}" "Decision questions must be self-contained" "adapter decision clarity ${file}"
  assert_contains "${file}" "question/recommendation-only choice table" "adapter no recommendation-only table ${file}"
  assert_contains "${file}" "compact option bundle" "adapter no compact option bundle ${file}"
  assert_contains "${file}" "Compact output is quality-preserving only" "adapter compact quality floor ${file}"
  assert_contains "${file}" "raw-source traceability" "adapter compact traceability ${file}"
  assert_contains "${file}" "use full clarity" "adapter compact full clarity fallback ${file}"
  assert_contains "${file}" "권장안 그대로 확정" "adapter natural confirmation phrase ${file}"
  assert_contains "${file}" 'Gate 3 (Plan) ready-for-implement routes to `sfs review --gate 3` first' "adapter plan review before implement ${file}"
  assert_contains "${file}" "Keep C-Level and worker/generator responsibilities separate" "adapter role split ${file}"
  assert_contains "${file}" "Gate 3 review must self-review until PASS before cross review" "adapter self before cross ${file}"
  assert_contains "${file}" "autopilot" "adapter same-cycle micro rework ${file}"
  assert_contains "${file}" "brainstorm/plan contract" "adapter autopilot micro rework ${file}"
  assert_contains "${file}" '"진행?"' "adapter no generic proceed ask ${file}"
  assert_contains "${file}" "User-call minimalism" "adapter user-call minimalism ${file}"
  assert_contains "${file}" "judgment" "adapter product judgment boundary ${file}"
  assert_contains "${file}" "User-escalation premise guard" "adapter premise guard ${file}"
  assert_contains "${file}" "cascade soft-delete" "adapter no invented cascade ${file}"
  assert_contains "${file}" "Executable Action Ownership" "adapter executable action ownership ${file}"
  assert_contains "${file}" "user explicitly asks for them or when" "adapter explicit command request exception ${file}"
  assert_contains "${file}" "truly blocked by" "adapter no runnable copy-paste handoff ${file}"
  assert_contains "${file}" "session-scoped authorization" "adapter session authorization ${file}"
  assert_contains "${file}" "agent-owned: use one-shot" "adapter shell state ownership ${file}"
  assert_contains "${file}" "secrets instead of asking" "adapter mask secrets ${file}"
  assert_contains "${file}" "sfs commit apply --group <name>" "adapter sfs commit command ${file}"
  assert_contains "${file}" "commits and pushes" "adapter sfs commit push ${file}"
  assert_contains "${file}" 'host-local `/commit` skill' "adapter no host-local commit skill ${file}"
  assert_contains "${file}" "Advisor calls do not count as self-CPO" "adapter advisor not self CPO ${file}"
  assert_contains "${file}" "self-CPO mini-check" "adapter self CPO mini check ${file}"
  assert_contains "${file}" 'normal worker slices use `gpt-5.4`' "adapter codex worker default ${file}"
  assert_contains "${file}" 'helpers use `gpt-5.3-codex`' "adapter codex coding helper ${file}"
  assert_contains "${file}" 'judgment-free' "adapter codex spark boundary ${file}"
  assert_contains "${file}" "applies by default" "adapter model routing default ${file}"
  assert_contains "${file}" "Helper-grade simple" "adapter helper-grade advisor exemption ${file}"
  assert_contains "${file}" '`gpt-5.4-mini`' "adapter codex intake model ${file}"
  assert_contains "${file}" '`gpt-5.4`' "adapter codex facilitator model ${file}"
  assert_contains "${file}" 'Sonnet 4.6' "adapter claude sonnet 4.6 ${file}"
  assert_contains "${file}" "Haiku is non-coding" "adapter haiku non-coding ${file}"
  assert_contains "${file}" "helper-only" "adapter haiku helper-only ${file}"
  assert_contains "${file}" '`gemini-3-pro-auto`' "adapter gemini 3 pro auto ${file}"
  assert_contains "${file}" "for every role" "adapter gemini every role ${file}"
  assert_not_contains "${file}" "Gemini high" "adapter no stale gemini high abstraction ${file}"
  assert_contains "${file}" "top-model advisor review" "adapter top advisor rule ${file}"
  assert_contains "${file}" "self-agent top-model" "adapter post-work self CPO ${file}"
  assert_contains "${file}" "Partial/fail redirects" "adapter post-work self CPO loop ${file}"
  assert_contains "${file}" "Multi-agent implement is optional, never the default" "adapter multi-agent optional ${file}"
  assert_contains "${file}" "clear native-language commit message" "adapter native commit message ${file}"
  assert_contains "${file}" "post-implement cross review is recorded before Gate 6" "adapter multi-agent cross review ${file}"
  assert_contains "${file}" "Taxonomy is a product function" "adapter taxonomy function ${file}"
  assert_contains "${file}" "machine-translate" "adapter no machine translation ${file}"
  assert_contains "${file}" "SFS command/domain terms" "adapter taxonomy terms ${file}"
  assert_contains "${file}" 'Other` or `Type something`' "adapter no placeholder UI ${file}"
  assert_contains "${file}" "one plain-language question" "adapter plain missing-arg question ${file}"
  assert_contains "${file}" "이번 sprint 목표를 한 줄로 말해 주세요" "adapter Korean start question ${file}"
  assert_contains "${file}" 'classify each checkpoint as `progressing`, `slow`' "adapter monitor state vocabulary ${file}"
  assert_contains "${file}" "commit delta, PR/head delta, local dirty state" "adapter monitor evidence fields ${file}"
  assert_contains "${file}" "lane-utilization evidence or waiver" "adapter monitor lane evidence ${file}"
  assert_contains "${file}" 'next action `wait`, `probe`' "adapter monitor next action ${file}"
  assert_contains "${file}" "request-response probe" "adapter monitor request-response liveness ${file}"
  assert_contains "${file}" "process/auth-status alone" "adapter monitor no process-only liveness ${file}"
  assert_contains "${file}" "static benign payload" "adapter monitor static probe ${file}"
  assert_contains "${file}" "workspace/user content" "adapter monitor no workspace content ${file}"
  assert_contains "${file}" "status/category/timestamp/redacted" "adapter monitor redacted evidence ${file}"
  assert_contains "${file}" "raw stdout/stderr" "adapter monitor no raw stdout ${file}"
  assert_contains "${file}" "bearer/auth tokens, env vars" "adapter monitor no auth/env persistence ${file}"
  assert_contains "${file}" "prompt bodies, model responses" "adapter monitor no prompt/model persistence ${file}"
  assert_contains "${file}" "workspace/user content, or PII" "adapter monitor no user/PII persistence ${file}"
  assert_contains "${file}" "heartbeat/automation cleanup" "adapter monitor cleanup ${file}"
  assert_contains "${file}" "durable wiki/report evidence" "adapter monitor durable evidence ${file}"
done

assert_contains "${plugin_readme}" 'classifies state as `progressing`, `slow`' "plugin readme monitor state vocabulary"
assert_contains "${plugin_readme}" "commit delta, PR/head delta, local dirty state" "plugin readme monitor evidence fields"
assert_contains "${plugin_readme}" "lane-utilization evidence or waiver" "plugin readme monitor lane evidence"
assert_contains "${plugin_readme}" "request-response probe, never" "plugin readme monitor liveness"
assert_contains "${plugin_readme}" "static benign payload" "plugin readme monitor static probe"
assert_contains "${plugin_readme}" "status/category/timestamp/redacted" "plugin readme monitor redacted evidence"
assert_contains "${plugin_readme}" "raw stdout/stderr, bearer/auth tokens, env vars" "plugin readme monitor no raw sensitive evidence"
assert_contains "${plugin_readme}" "heartbeat/automation cleanup and durable wiki/report" "plugin readme monitor close evidence"

echo "test-agent-behavior-guardrails: OK"
