#!/usr/bin/env bash
# SFS 에이전트 행동 가드레일이 런타임 컨텍스트와 어댑터에 남아 있는지 검증한다.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_contains() {
  local file="$1"
  local needle="$2"
  local label="$3"

  [[ -f "${file}" ]] || fail "${label}: missing file ${file}"
  grep -Fq -- "${needle}" "${file}" || fail "${label}: missing '${needle}'"
}

assert_not_contains() {
  local file="$1"
  local needle="$2"
  local label="$3"

  [[ -f "${file}" ]] || fail "${label}: missing file ${file}"
  if grep -Fq -- "${needle}" "${file}"; then
    fail "${label}: unexpected '${needle}'"
  fi
}

kernel="${DIST_DIR}/templates/.sfs-local-template/context/kernel.md"
brainstorm="${DIST_DIR}/templates/.sfs-local-template/context/commands/brainstorm.md"
plan="${DIST_DIR}/templates/.sfs-local-template/context/commands/plan.md"
implement="${DIST_DIR}/templates/.sfs-local-template/context/commands/implement.md"
review="${DIST_DIR}/templates/.sfs-local-template/context/commands/review.md"
tidy="${DIST_DIR}/templates/.sfs-local-template/context/commands/tidy.md"
plan_template="${DIST_DIR}/templates/.sfs-local-template/sprint-templates/plan.md"
review_script="${DIST_DIR}/templates/.sfs-local-template/scripts/sfs-review.sh"
common_script="${DIST_DIR}/templates/.sfs-local-template/scripts/sfs-common.sh"
model_profiles="${DIST_DIR}/templates/.sfs-local-template/model-profiles.yaml"
researcher="${DIST_DIR}/templates/.sfs-local-template/personas/researcher.md"
cpo="${DIST_DIR}/templates/.sfs-local-template/personas/cpo-evaluator.md"
installer="${DIST_DIR}/install.sh"
upgrader="${DIST_DIR}/upgrade.sh"
claude_template="${DIST_DIR}/templates/CLAUDE.md.template"
agents_template="${DIST_DIR}/templates/AGENTS.md.template"
gemini_template="${DIST_DIR}/templates/GEMINI.md.template"
sfs_template="${DIST_DIR}/templates/SFS.md.template"
codex_skill_template="${DIST_DIR}/templates/codex-skill/SKILL.md"
plugin_command="${DIST_DIR}/plugins/solon/commands/sfs.md"
plugin_readme="${DIST_DIR}/plugins/solon/README.md"

assert_contains "${kernel}" "surface material assumptions" "kernel assumptions"
assert_contains "${kernel}" "minimum useful slice" "kernel simplicity"
assert_contains "${kernel}" "Read actual files, command output, and error logs" "kernel evidence"
assert_contains "${kernel}" "do not end Korean sentences with a closing colon" "kernel Korean output"
assert_contains "${kernel}" "current SFS workbench artifacts" "kernel SFS notes"
assert_contains "${kernel}" "Multi-agent work is thin supervision" "kernel thin supervision"
assert_contains "${kernel}" "Decision questions must be self-contained" "kernel decision clarity"
assert_contains "${kernel}" "question/recommendation-only table" "kernel no recommendation-only choice table"
assert_contains "${kernel}" "show every viable option" "kernel all options visible"
assert_contains "${kernel}" "ask one decision at a time" "kernel sequential decision fallback"
assert_contains "${kernel}" "compact option bundle" "kernel no compact option bundle"
assert_contains "${kernel}" "권장안 그대로 확정" "kernel natural confirmation phrase"
assert_contains "${kernel}" "Gate order is a runtime contract" "kernel gate order"
assert_contains "${kernel}" "Review verdicts are success criteria, not effort counters" "kernel review verdict"
assert_contains "${kernel}" "Advisor review is not a self-CPO PASS" "kernel advisor not self CPO"
assert_contains "${kernel}" "Missing self-CPO evidence is partial" "kernel self CPO missing partial"
assert_contains "${kernel}" "Cross review comes after local self-review passes" "kernel self before cross"
assert_contains "${kernel}" "Role split is invariant" "kernel role split"
assert_contains "${kernel}" 'default worker/generator model is `gpt-5.3-codex`' "kernel codex worker default"
assert_contains "${kernel}" '`gpt-5.3-codex-spark` is reserved' "kernel codex spark boundary"
assert_contains "${kernel}" "Taxonomy is a product function" "kernel taxonomy function"
assert_contains "${kernel}" "one plain-language question" "kernel missing arg question"
assert_contains "${kernel}" 'Other` or `Type something`' "kernel placeholder labels"
assert_contains "${kernel}" "이번 sprint 목표를 한 줄로 말해 주세요" "kernel Korean start question"

assert_contains "${brainstorm}" "docs/solon/domain-map.md" "brainstorm domain map"
assert_contains "${brainstorm}" "read-only researcher" "brainstorm researcher"
assert_contains "${brainstorm}" "A/A/A/C/C 확정" "brainstorm no compact bundle confirmation"
assert_contains "${brainstorm}" "권장안 다시 보여줘" "brainstorm recommendation replay guard"

assert_contains "${plan}" "explicit non-goals" "plan tradeoffs"
assert_contains "${plan}" "verify by ..." "plan verification"
assert_contains "${plan}" "mandatory" "plan no root notes"
assert_contains "${plan}" "root-level" "plan no root notes"
assert_contains "${plan}" "sfs review --gate 3" "plan pre-implementation review"
assert_contains "${plan}" "Gate 3 plan review is mandatory before implementation" "plan mandatory review"
assert_contains "${plan}" 'Do not offer `sfs implement`, worker delegation, or model-selection choices' "plan no direct implement action rail"
assert_contains "${plan}" "plan until PASS first, then run cross review" "plan self before cross"
assert_contains "${plan}" "self-CPO mini-check, not only advisor consultation" "plan self CPO not advisor"
assert_contains "${plan}" "SEED, placeholder, mock, or fallback" "plan seed placeholder non acceptance"
assert_contains "${plan}" "Do not use review volume as a stopping rule" "plan no review volume stop"
assert_contains "${plan}" "C-Level owns the contract" "plan C-Level boundary"
assert_contains "${plan}" "recommended worker default is" "plan codex worker default"
assert_contains "${plan}" 'Do not offer `gpt-5.3-codex-spark` as the normal worker' "plan codex spark boundary"
assert_contains "${plan}" "docs/solon/domain-map.md" "plan domain map"
assert_contains "${plan}" "do not end with" "plan decision clarity"
assert_contains "${plan}" 'unexplained `Q1`' "plan unexplained Q1 guardrail"
assert_contains "${plan}" "Never show only the recommended column" "plan no recommendation-only choices"
assert_contains "${plan}" 'Define labels such as `A/B/C/D` inline' "plan option label definitions"
assert_contains "${plan}" "ask the decisions sequentially" "plan sequential choices"
assert_contains "${plan}" "compact bundle confirmations" "plan no compact bundle confirmation"
assert_contains "${plan}" "권장안 다시 보여줘" "plan recommendation replay guard"
assert_contains "${plan}" "avoid translationese" "plan no translationese review readiness"
assert_contains "${plan}" "files/artifacts are mapped per slice" "plan review readiness slice mapping"

assert_contains "${plan_template}" "Gate 2 결정이 요구사항과 AC에 연결되어 있다" "plan template Gate 2 decision mapping"
assert_contains "${plan_template}" "slice별 파일/산출물 매핑이 있다" "plan template slice artifact mapping"
assert_contains "${plan_template}" "Spark는 scope/files_scope/AC가 잠긴 기계적 구현 보조 작업에만 쓴다" "plan template Spark boundary"
assert_not_contains "${plan_template}" "열린 결정이 이름 붙어 있다" "plan template no awkward open-decision wording"

assert_contains "${implement}" "Keep changes surgical" "implement surgical changes"
assert_contains "${implement}" "speculative flexibility" "implement simplicity"
assert_contains "${implement}" "dirty" "implement worktree respect"
assert_contains "${implement}" "worktree changes" "implement worktree respect"
assert_contains "${implement}" "full error/log output" "implement read errors"
assert_contains "${implement}" "smallest relevant test" "implement verification"
assert_contains "${implement}" ".sfs-local/personas/researcher.md" "implement researcher"
assert_contains "${implement}" "files_scope explicit and disjoint" "implement worker scope"
assert_contains "${implement}" "requires a Gate 3 Plan review PASS" "implement preflight review"
assert_contains "${implement}" "default implementation owner is the worker/generator model" "implement worker model default"
assert_contains "${implement}" 'recommended worker default is `gpt-5.3-codex`' "implement codex worker default"
assert_contains "${implement}" '`gpt-5.3-codex-spark` is not the normal implementation owner' "implement codex spark boundary"
assert_contains "${implement}" "Self-review must pass first; cross review follows" "implement self before cross"
assert_contains "${implement}" "Agent mode is an implementation-time choice" "implement agent mode choice"
assert_contains "${implement}" "Default to single-agent" "implement single default"
assert_contains "${implement}" "--agent-mode parallel --agents codex,claude[,gemini]" "implement parallel option"
assert_contains "${implement}" "one-sentence proposed commit" "implement commit unit guard"
assert_contains "${implement}" "native/workspace language" "implement native commit language"
assert_contains "${implement}" "After any implementation" "implement post review required"
assert_contains "${implement}" "cross review between agents is required" "implement parallel cross review"

assert_contains "${review}" "Review actual diff, files, test output, and logs" "review evidence"
assert_contains "${review}" "Gate 3 plan review is the required bridge between plan and implement" "review plan-to-implement bridge"
assert_contains "${review}" "Gate 3 review has a sequence: local self-review until PASS" "review self before cross"
assert_contains "${review}" "Local self-review means a self-CPO mini-check" "review self CPO meaning"
assert_contains "${review}" "If that evidence is absent, return partial" "review self CPO missing partial"
assert_contains "${review}" "Number of lenses, rounds, advisor" "review no volume pass"
assert_contains "${review}" "Flag overengineering" "review overengineering"
assert_contains "${review}" "Repeated review for the same sprint/gate must converge" "review lens convergence"
assert_contains "${review}" "later auto reviews reuse that" "review auto lens lock"
assert_contains "${review}" "exact verification command/result" "review verification evidence"
assert_contains "${review}" "self-validation risk" "review self-validation"
assert_contains "${review}" "agent_mode: parallel" "review parallel mode"
assert_contains "${review}" "disjoint files_scope per lane" "review parallel scope"
assert_contains "${review}" "commit message per lane" "review parallel commit message"
assert_contains "${review}" "native/workspace language" "review native commit language"
assert_contains "${review}" "cross review" "review parallel cross review"
assert_contains "${review}" 'Pass should name `sfs retro` as the' "review retro close path"
assert_contains "${tidy}" 'Do not recommend `report` before `retro`' "tidy no report-before-retro"
assert_contains "${review_script}" 'name `/sfs retro` as the normal close path' "review prompt retro close path"
assert_contains "${review_script}" "Advisor calls are not a self-CPO PASS" "review prompt advisor not self CPO"
assert_contains "${review_script}" "SFS_REVIEW_BRIDGE_PROBE_TIMEOUT_SEC" "review bridge probe timeout"
assert_contains "${review_script}" "CPO evaluator bridge probe failed before full review" "review bridge probe fail fast"
assert_contains "${review_script}" "SFS_REVIEW_BRIDGE_PROBE_OK" "review bridge probe marker"
assert_contains "${review_script}" 'claude -p "$(cat)"' "review claude prompt-argument bridge"
assert_not_contains "${review_script}" "claude -p --dangerously-skip-permissions" "review no stale claude dangerous stdin bridge"
assert_contains "${common_script}" 'eval "exec ${cmd}"' "common executor timeout kills real CLI"
assert_contains "${common_script}" "SFS_REVIEW_<EXECUTOR>_CMD override; do not widen" "common eval allow-list comment"
assert_contains "${common_script}" 'claude -p "$(cat)"' "common claude prompt-argument bridge"
assert_not_contains "${common_script}" "claude -p --dangerously-skip-permissions" "common no stale claude dangerous stdin bridge"
stale_report_cmd='/sfs report'
stale_retro_cmd='/sfs retro'
stale_close_phrase="usually \`${stale_report_cmd}\` then \`${stale_retro_cmd}\`"
assert_not_contains "${review_script}" "${stale_close_phrase}" "review prompt no stale report-then-retro"

assert_contains "${researcher}" "default_executor: gemini" "researcher default executor"
assert_contains "${researcher}" "Do not edit production files" "researcher read-only"
assert_contains "${researcher}" "docs/solon/domain-map.md" "researcher domain map"
assert_contains "${cpo}" "Advisor calls do not satisfy self-CPO" "cpo advisor not self CPO"
assert_contains "${cpo}" "lacks self-CPO evidence" "cpo missing self CPO partial"

assert_contains "${model_profiles}" "research_high" "model profiles research tier"
assert_contains "${model_profiles}" "intake_economy" "model profiles intake tier"
assert_contains "${model_profiles}" "facilitator_standard" "model profiles facilitator tier"
assert_contains "${model_profiles}" "default_applied" "model profiles default applied status"
assert_contains "${model_profiles}" "selected_policy=solon_recommended" "model profiles recommended default rule"
assert_contains "${model_profiles}" "researcher: research_high" "model profiles researcher policy"
assert_contains "${model_profiles}" ".sfs-local/personas/researcher.md" "model profiles researcher persona"
assert_contains "${model_profiles}" "role_boundaries" "model profiles role boundaries"
assert_contains "${model_profiles}" "self_cpo_check" "model profiles self CPO boundary"
assert_contains "${model_profiles}" "self-cpo-checker" "model profiles self CPO agent"
assert_contains "${model_profiles}" "Helper-grade simple I/O" "model profiles helper-grade advisor exemption"
assert_contains "${model_profiles}" "top-model strategic_high advisor" "model profiles top advisor rule"
assert_contains "${model_profiles}" "Advisor consultation is not self-CPO" "model profiles advisor not self CPO"
assert_contains "${model_profiles}" "Gate 3 Plan review must pass before worker/generator implementation starts" "model profiles gate invariant"
assert_contains "${model_profiles}" "Single-agent implementation is the default" "model profiles single default"
assert_contains "${model_profiles}" "Multi-agent implementation is opt-in" "model profiles parallel opt-in"
assert_contains "${model_profiles}" 'model: "gpt-5.4-mini"' "model profiles codex intake model"
assert_contains "${model_profiles}" 'model: "gpt-5.4"' "model profiles codex facilitator model"
assert_contains "${model_profiles}" 'model: "gpt-5.3-codex"' "model profiles codex worker model"
assert_contains "${model_profiles}" 'model: "gpt-5.3-codex-spark"' "model profiles codex spark helper"
assert_contains "${model_profiles}" 'model: "gemini-3.1-pro-preview"' "model profiles gemini 3.1 pro default"
assert_contains "${model_profiles}" 'model: "gemini-3-flash-preview"' "model profiles gemini 3 flash fallback"
assert_not_contains "${model_profiles}" "gemini-2.5" "model profiles no gemini 2.5 fallback"
assert_contains "${model_profiles}" "not gpt-5.5 and not gpt-5.3-codex-spark" "model profiles codex worker rule"
assert_contains "${review_script}" 'For Codex CPO/cross review, the requested review_high profile is gpt-5.5 with xhigh reasoning.' "review codex prompt review_high"
assert_contains "${review_script}" 'The default Codex shell bridge does not force model selection with CLI flags' "review codex prompt routing"
assert_contains "${review_script}" 'codex exec --full-auto --ephemeral --output-last-message \"${RUN_RESULT}\" -' "review codex prompt-based bridge"
assert_not_contains "${review_script}" 'SFS_REVIEW_CODEX_MODEL:-gpt-5.5' "review codex no default model cli flag"
assert_not_contains "${review_script}" 'SFS_REVIEW_CODEX_REASONING_EFFORT:-xhigh' "review codex no default reasoning cli flag"
assert_contains "${installer}" 'MODEL_POLICY="${SFS_MODEL_POLICY:-solon_recommended}"' "install recommended default"
assert_contains "${installer}" '[ "$MODEL_POLICY" != "solon_recommended" ]' "install preserves default-applied status"
assert_contains "${installer}" "agent model profile 기본값 적용" "install no prompt default"
assert_contains "${installer}" "gemini-3.1-pro-preview" "install gemini 3.1 pro default"
assert_contains "${installer}" "2.5 fallback 은 쓰지 않습니다" "install no gemini 2.5 fallback"
assert_contains "${installer}" "advisor 호출은 self-CPO PASS 가 아닙니다" "install advisor not self CPO"
assert_contains "${upgrader}" "MODEL_POLICY=\"solon_recommended\"" "upgrade recommended default"
assert_contains "${upgrader}" "solon_recommended 기본 role routing" "upgrade fallback migration"
assert_contains "${upgrader}" "gemini-3.1-pro-preview" "upgrade gemini 3.1 pro default"
assert_contains "${upgrader}" "2.5 fallback 은 쓰지 않습니다" "upgrade no gemini 2.5 fallback"
assert_contains "${upgrader}" "advisor 호출은 self-CPO PASS 가 아닙니다" "upgrade advisor not self CPO"

for handoff_doc in \
  "${claude_template}" \
  "${agents_template}" \
  "${gemini_template}" \
  "${sfs_template}" \
  "${codex_skill_template}" \
  "${plugin_command}" \
  "${plugin_readme}"
do
  assert_contains "${handoff_doc}" "docs/solon/<english-workspace>/<yyyyMMdd>/" "handoff docs root path ${handoff_doc}"
done
assert_not_contains "${claude_template}" "docs/<workspace>/<yyyyMMdd>/" "claude no stale root docs handoff"
assert_not_contains "${agents_template}" "docs/<workspace>/<yyyyMMdd>/" "agents no stale root docs handoff"
assert_not_contains "${gemini_template}" "docs/<workspace>/<yyyyMMdd>/" "gemini no stale root docs handoff"
assert_not_contains "${sfs_template}" "docs/<workspace>/<yyyyMMdd>/" "SFS no stale root docs handoff"
assert_contains "${sfs_template}" "compact option bundle" "SFS no compact option bundle"
assert_contains "${sfs_template}" "권장안 그대로 확정" "SFS natural confirmation phrase"

adapter_files=(
  "${DIST_DIR}/templates/CLAUDE.md.template"
  "${DIST_DIR}/templates/AGENTS.md.template"
  "${DIST_DIR}/templates/GEMINI.md.template"
  "${DIST_DIR}/templates/codex-skill/SKILL.md"
  "${DIST_DIR}/templates/.agents/skills/sfs/SKILL.md"
  "${DIST_DIR}/templates/.claude/commands/sfs.md"
  "${DIST_DIR}/templates/.gemini/commands/sfs.toml"
  "${DIST_DIR}/templates/.codex/prompts/sfs.md"
  "${DIST_DIR}/commands/sfs.toml"
  "${DIST_DIR}/plugins/solon/commands/sfs.md"
)

for file in "${adapter_files[@]}"; do
  assert_contains "${file}" "surface material assumptions" "adapter guardrail ${file}"
  assert_contains "${file}" "report exact evidence" "adapter evidence ${file}"
  assert_contains "${file}" "Decision questions must be self-contained" "adapter decision clarity ${file}"
  assert_contains "${file}" "question/recommendation-only choice table" "adapter no recommendation-only table ${file}"
  assert_contains "${file}" "compact option bundle" "adapter no compact option bundle ${file}"
  assert_contains "${file}" "권장안 그대로 확정" "adapter natural confirmation phrase ${file}"
  assert_contains "${file}" 'Gate 3 (Plan) ready-for-implement routes to `sfs review --gate 3` first' "adapter plan review before implement ${file}"
  assert_contains "${file}" "Keep C-Level and worker/generator responsibilities separate" "adapter role split ${file}"
  assert_contains "${file}" "Gate 3 review must self-review until PASS before cross review" "adapter self before cross ${file}"
  assert_contains "${file}" "Advisor calls do not count as self-CPO" "adapter advisor not self CPO ${file}"
  assert_contains "${file}" "self-CPO mini-check" "adapter self CPO mini check ${file}"
  assert_contains "${file}" 'Codex worker default is `gpt-5.3-codex`' "adapter codex worker default ${file}"
  assert_contains "${file}" '`gpt-5.3-codex-spark` is helper-only' "adapter codex spark boundary ${file}"
  assert_contains "${file}" "Model routing applies by default" "adapter model routing default ${file}"
  assert_contains "${file}" "Helper-grade simple" "adapter helper-grade advisor exemption ${file}"
  assert_contains "${file}" '`gpt-5.4-mini`' "adapter codex intake model ${file}"
  assert_contains "${file}" '`gpt-5.4`' "adapter codex facilitator model ${file}"
  assert_contains "${file}" '`gemini-3.1-pro-preview`' "adapter gemini 3.1 advisor ${file}"
  assert_not_contains "${file}" "Gemini high" "adapter no stale gemini high abstraction ${file}"
  assert_contains "${file}" "top-model advisor review" "adapter top advisor rule ${file}"
  assert_contains "${file}" "Multi-agent implement is optional, never the default" "adapter multi-agent optional ${file}"
  assert_contains "${file}" "clear native-language commit message" "adapter native commit message ${file}"
  assert_contains "${file}" "post-implement cross review is recorded before Gate 6" "adapter multi-agent cross review ${file}"
  assert_contains "${file}" "Taxonomy is a product function" "adapter taxonomy function ${file}"
  assert_contains "${file}" "machine-translate" "adapter no machine translation ${file}"
  assert_contains "${file}" "SFS command/domain terms" "adapter taxonomy terms ${file}"
  assert_contains "${file}" 'Other` or `Type something`' "adapter no placeholder UI ${file}"
  assert_contains "${file}" "one plain-language question" "adapter plain missing-arg question ${file}"
  assert_contains "${file}" "이번 sprint 목표를 한 줄로 말해 주세요" "adapter Korean start question ${file}"
done

echo "test-agent-behavior-guardrails: OK"
