#!/usr/bin/env bash
# Obsidian LLM wiki guidance must be recommended, routed, and non-blocking.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONTEXT_DIR="${DIST_DIR}/templates/.sfs-local-template/context"
SFS_TEMPLATE_DIR="${DIST_DIR}/templates/.sfs-local-template"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_contains() {
  local file="$1" needle="$2" label="$3"
  [[ -f "${file}" ]] || fail "${label}: missing ${file}"
  grep -Fq -- "${needle}" "${file}" || fail "${label}: missing '${needle}'"
}

policy="${CONTEXT_DIR}/policies/obsidian-llm-wiki.md"
policy_ko="${CONTEXT_DIR}/policies/obsidian-llm-wiki.ko.md"

assert_contains "${policy}" "recommended companion" "EN policy recommended"
assert_contains "${policy}" "not a coercive dependency" "EN policy non-coercive"
assert_contains "${policy}" "New project" "EN policy new project flow"
assert_contains "${policy}" "Existing project" "EN policy existing project flow"
assert_contains "${policy}" "Applied project" "EN policy applied project flow"
assert_contains "${policy}" "Build an Obsidian wiki by reference" "EN policy by-reference migration"
assert_contains "${policy}" 'DDD operating model root: `llm-wiki/ddd/`' "EN policy DDD folder"
assert_contains "${policy}" "Raw / Wiki / Schema (+lint)" "EN policy three-layer model (canonical)"
assert_contains "${policy}" "write-time compiled" "EN policy write-time compile"
assert_contains "${policy}" "external source manager" "EN policy external source manager"
assert_contains "${policy}" "Source-bundle analysis tools are derived workspaces" "EN policy source-bundle derived workspace"
assert_contains "${policy}" "RAG/vector search is an optional query-time accelerator" "EN policy RAG accelerator"
assert_contains "${policy}" "not the source of truth or a fact guarantee" "EN policy RAG no fact guarantee"
assert_contains "${policy}" "parser/chunk/retriever smoke evidence" "EN policy RAG evidence"
assert_contains "${policy}" "Product identity boundary" "EN policy product identity boundary"
assert_contains "${policy}" "instead of Solon product scope" "EN policy defer wiki tooling"
assert_contains "${policy}" "shared knowledge changes need human review" "EN policy human review"
assert_contains "${policy}" "Taxonomy is not a standalone wiki" "EN policy taxonomy boundary"
assert_contains "${policy}" "Host-local tool/skill bundles and user-home folders are external environment" "EN policy host-local boundary"
assert_contains "${policy}" "not project SSoT, wiki roots, install targets, or migration sources" "EN policy no host-local SoT"
assert_contains "${policy}" "If a concept has already been absorbed by SFS" "EN policy SFS absorbed concepts"
assert_contains "${policy}" "project context instead of skipping it" "EN policy active context review"
assert_contains "${policy}" '`llm-wiki/ddd/README.md` or a recorded DDD wiki gap/waiver' "EN policy DDD evidence"
assert_contains "${policy}" "Never commit personal workspace state" "EN policy workspace boundary"
assert_contains "${policy}" 'sfs tidy --wiki-promote' "EN policy docs GC promotion"
assert_contains "${policy}" "promotion-candidates" "EN policy promotion candidates"
assert_contains "${policy_ko}" "권장" "KO policy recommended"
assert_contains "${policy_ko}" "필수 의존성처럼 강제하지 않는다" "KO policy non-coercive"
assert_contains "${policy_ko}" "신규 프로젝트" "KO policy new project flow"
assert_contains "${policy_ko}" "기존 프로젝트" "KO policy existing project flow"
assert_contains "${policy_ko}" "적용 프로젝트" "KO policy applied project flow"
assert_contains "${policy_ko}" "by-reference" "KO policy by-reference migration"
assert_contains "${policy_ko}" 'DDD 운영 모델 root: `llm-wiki/ddd/`' "KO policy DDD folder"
assert_contains "${policy_ko}" "Raw / Wiki / Schema (+lint)" "KO policy three-layer model (canonical)"
assert_contains "${policy_ko}" "write-time compile" "KO policy write-time compile"
assert_contains "${policy_ko}" "외부 source manager" "KO policy external source manager"
assert_contains "${policy_ko}" "source-bundle 분석 도구 결과" "KO policy source-bundle derived output"
assert_contains "${policy_ko}" "RAG/vector search 는 curated source/wiki metadata" "KO policy RAG accelerator"
assert_contains "${policy_ko}" "fact 보장 장치가 아니다" "KO policy RAG no fact guarantee"
assert_contains "${policy_ko}" "source citation, no-answer behavior" "KO policy RAG evidence"
assert_contains "${policy_ko}" "제품 방향이 아니며" "KO policy product identity boundary"
assert_contains "${policy_ko}" "shared knowledge 변경은 merge 전" "KO policy human review"
assert_contains "${policy_ko}" "Taxonomy 는 독립 wiki 나 조직 본부가 아니다" "KO policy taxonomy boundary"
assert_contains "${policy_ko}" "host-local tool/skill bundle 과 user-home folder 는 외부 실행 환경" "KO policy host-local boundary"
assert_contains "${policy_ko}" "project SSoT, wiki root" "KO policy no host-local SoT"
assert_contains "${policy_ko}" "이미 SFS 에 흡수된 개념" "KO policy SFS absorbed concepts"
assert_contains "${policy_ko}" "active project context 로 취급했는가" "KO policy active context review"
assert_contains "${policy_ko}" 'sfs tidy' "KO policy docs GC promotion"
assert_contains "${policy_ko}" "promotion-candidates" "KO policy promotion candidates"

assert_contains "${CONTEXT_DIR}/_INDEX.md" "policies/obsidian-llm-wiki.md" "context index routes policy"
assert_contains "${CONTEXT_DIR}/kernel.md" "Obsidian LLM wiki is a recommended companion" "kernel recommended"
assert_contains "${CONTEXT_DIR}/kernel.md" "not a hard dependency" "kernel non-blocking"
assert_contains "${CONTEXT_DIR}/kernel.md" 'If `.obsidian/` or `llm-wiki/` exists' "kernel applied wiki detection"
assert_contains "${CONTEXT_DIR}/kernel.md" '`llm-wiki/ddd/README.md` before broad' "kernel DDD wiki pre-scan"
assert_contains "${CONTEXT_DIR}/kernel.md" "Host-local tool/skill bundles and user-home folders are external environment" "kernel host-local boundary"
assert_contains "${CONTEXT_DIR}/commands/start.md" "For a new SFS project" "start new project guidance"
assert_contains "${CONTEXT_DIR}/commands/start.md" "not a blocker" "start non-blocking"
assert_contains "${CONTEXT_DIR}/commands/adopt.md" "For existing projects with meaningful docs" "adopt existing project guidance"
assert_contains "${CONTEXT_DIR}/commands/adopt.md" "sfs start \"Obsidian LLM wiki baseline\"" "adopt next sprint"
assert_contains "${CONTEXT_DIR}/commands/plan.md" "policies/obsidian-llm-wiki.md" "plan loads policy"
assert_contains "${CONTEXT_DIR}/commands/implement.md" 'If `llm-wiki/` exists' "implement updates wiki maps"
assert_contains "${CONTEXT_DIR}/commands/implement.md" "durable retrieval across" "implement durable retrieval"
assert_contains "${CONTEXT_DIR}/policies/knowledge-pack-router.md" "Obsidian/wiki signals" "EN router signals"
assert_contains "${CONTEXT_DIR}/policies/knowledge-pack-router.ko.md" "Obsidian/wiki signals" "KO router signals"

assert_contains "${DIST_DIR}/templates/.gitignore.snippet" ".obsidian/workspace.json" "gitignore workspace"
assert_contains "${DIST_DIR}/templates/.gitignore.snippet" ".obsidian/plugins/" "gitignore plugins"
assert_contains "${SFS_TEMPLATE_DIR}/scripts/sfs-common.sh" "sfs_maybe_emit_obsidian_wiki_notice" "runtime obsidian notice helper"
assert_contains "${SFS_TEMPLATE_DIR}/scripts/sfs-common.sh" "Obsidian project surface detected" "runtime obsidian surface detection"
assert_contains "${SFS_TEMPLATE_DIR}/scripts/sfs-common.sh" "Host-local tools/user-home folders are external environment" "runtime host-local notice"
assert_contains "${SFS_TEMPLATE_DIR}/scripts/sfs-dispatch.sh" "sfs_maybe_emit_obsidian_wiki_notice" "dispatch obsidian notice hook"
assert_contains "${DIST_DIR}/templates/codex-skill/SKILL.md" "Obsidian LLM wiki is a recommended companion" "codex skill"
assert_contains "${DIST_DIR}/templates/codex-skill/SKILL.md" 'If `.obsidian/` or' "codex skill active wiki"
assert_contains "${DIST_DIR}/templates/codex-skill/SKILL.md" "Host-local tool/skill bundles and user-home folders are external" "codex skill host-local boundary"
assert_contains "${DIST_DIR}/templates/.agents/skills/sfs/SKILL.md" "Obsidian LLM wiki is a recommended companion" "agents skill"
assert_contains "${DIST_DIR}/templates/.agents/skills/sfs/SKILL.md" 'If `.obsidian/` or' "agents skill active wiki"
assert_contains "${DIST_DIR}/templates/.agents/skills/sfs/SKILL.md" "Host-local tool/skill bundles and user-home folders are external" "agents skill host-local boundary"
assert_contains "${DIST_DIR}/docs/en/current-product-shape.md" "19-obsidian-llm-wiki-continuity.md" "EN product index"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape.md" "19-obsidian-llm-wiki-continuity.md" "KO product index"
assert_contains "${DIST_DIR}/docs/en/current-product-shape/19-obsidian-llm-wiki-continuity.md" "recommended default, not a hard dependency" "EN product non-blocking"
assert_contains "${DIST_DIR}/docs/en/current-product-shape/19-obsidian-llm-wiki-continuity.md" "write-time compiled concept/navigation layer" "EN product write-time compile"
assert_contains "${DIST_DIR}/docs/en/current-product-shape/19-obsidian-llm-wiki-continuity.md" "RAG/vector search can still help" "EN product RAG boundary"
assert_contains "${DIST_DIR}/docs/en/current-product-shape/19-obsidian-llm-wiki-continuity.md" "wiki growth serves SFS flow" "EN product product identity boundary"
assert_contains "${DIST_DIR}/docs/en/current-product-shape/19-obsidian-llm-wiki-continuity.md" "docs GC pre-pass" "EN product docs GC"
assert_contains "${DIST_DIR}/docs/en/current-product-shape/19-obsidian-llm-wiki-continuity.md" "Host-local tool/skill bundles and user-home folders are external environment" "EN product host-local boundary"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape/19-obsidian-llm-wiki-continuity.md" "권고 기본값이지 hard dependency" "KO product non-blocking"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape/19-obsidian-llm-wiki-continuity.md" "wiki 는 write-time compile 된 concept/navigation layer" "KO product write-time compile"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape/19-obsidian-llm-wiki-continuity.md" "RAG/vector search 는 계속 쓸 수 있지만" "KO product RAG boundary"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape/19-obsidian-llm-wiki-continuity.md" "제품 방향이 아닙니다" "KO product product identity boundary"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape/19-obsidian-llm-wiki-continuity.md" "docs GC pre-pass" "KO product docs GC"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape/19-obsidian-llm-wiki-continuity.md" "host-local tool/skill bundle 과 user-home folder 는 외부 실행 환경" "KO product host-local boundary"

echo "test-obsidian-llm-wiki-guidance: OK"
