#!/usr/bin/env bash
# Windows wrapper incident report documentation guard.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_contains() {
  local file="$1"
  local needle="$2"
  local label="$3"

  [[ -f "${file}" ]] || fail "${label}: missing ${file}"
  grep -Fq -- "${needle}" "${file}" || fail "${label}: missing '${needle}'"
}

ko_report="${DIST_DIR}/docs/ko/windows-wrapper-incident-0.6.56.md"
en_report="${DIST_DIR}/docs/en/windows-wrapper-incident-0.6.56.md"
changelog="${DIST_DIR}/CHANGELOG.md"
release_notes="${DIST_DIR}/RELEASE-NOTES.md"

if [[ ! -f "${changelog}" && -f "${DIST_DIR}/../CHANGELOG.md" ]]; then
  changelog="${DIST_DIR}/../CHANGELOG.md"
fi
if [[ ! -f "${release_notes}" && -f "${DIST_DIR}/../RELEASE-NOTES.md" ]]; then
  release_notes="${DIST_DIR}/../RELEASE-NOTES.md"
fi

assert_contains "${ko_report}" "fatal error - couldn't create signal pipe, Win32 error 5" "KO report Win32 error"
assert_contains "${ko_report}" "sfs.cmd -> sfs.ps1 -> Bash runtime" "KO report fixed bridge"
assert_contains "${ko_report}" "usage-only" "KO report usage-only"
assert_contains "${ko_report}" "한국어 깨짐" "KO report mojibake"
assert_contains "${ko_report}" "sfs.cmd start \"이미지 프롬프트 고도화\"" "KO report repro command"
assert_contains "${ko_report}" "Homebrew installed layout" "KO report installed layout"
assert_contains "${ko_report}" "TIVE_READONLY_DONE" "KO report batch replacement tail"
assert_contains "${ko_report}" '`e`, `*`' "KO report short replacement tail"
assert_contains "${ko_report}" 'Windows self-upgrade 의 소유자는 `sfs.ps1`' "KO report ps1 self-upgrade owner"
assert_contains "${ko_report}" "같은 parsed line" "KO report same-line exit"
assert_contains "${ko_report}" "ASCII-only" "KO report ASCII-only parser guard"
assert_contains "${ko_report}" "SFS_ORIGINAL_ARGS" "KO report cached arg finding"
assert_contains "${ko_report}" 'call-label `%*`' "KO report direct percent-star forwarding"
assert_contains "${ko_report}" "batch label forwarding" "KO report batch label finding"
assert_contains "${ko_report}" "call-label dispatch 없는 thin PowerShell trampoline" "KO report thin cmd trampoline"
assert_contains "${ko_report}" 'powershell.exe -File sfs.ps1 %*' "KO report powershell file finding"
assert_contains "${ko_report}" 'SFS_NATIVE_SCRIPT @args' "KO report powershell command bridge"
assert_contains "${ko_report}" 'SFS_NATIVE_ARGC' "KO report env arg count bridge"
assert_contains "${ko_report}" 'SFS_NATIVE_ARG_N' "KO report numbered env arg bridge"
assert_contains "${ko_report}" 'PowerShell CLI argument binding' "KO report CLI argv binding finding"
assert_contains "${ko_report}" 'CMDCMDLINE' "KO report cmdcmdline fallback"
assert_contains "${ko_report}" 'empty `%1..%n`' "KO report empty numbered args finding"
assert_contains "${ko_report}" 'bin\sfs.ps1' "KO report Scoop ps1 shim target"
assert_contains "${ko_report}" '25533332634' "KO report 0.6.45 failed smoke run"
assert_contains "${ko_report}" '25534566676' "KO report 0.6.46 failed smoke run"
assert_contains "${ko_report}" '25535059980' "KO report 0.6.47 failed smoke run"
assert_contains "${ko_report}" '25539387684' "KO report 0.6.48 failed smoke run"
assert_contains "${ko_report}" '25541086874' "KO report 0.6.49 failed smoke run"
assert_contains "${ko_report}" '25542777986' "KO report 0.6.50 failed smoke run"
assert_contains "${ko_report}" '25543802195' "KO report 0.6.51 failed smoke run"
assert_contains "${ko_report}" '25545120029' "KO report 0.6.52 failed smoke run"
assert_contains "${ko_report}" '25546859759' "KO report 0.6.53 failed smoke run"
assert_contains "${ko_report}" '25548381094' "KO report 0.6.54 failed smoke run"
assert_contains "${ko_report}" 'automatic `$args`' "KO report automatic args path"
assert_contains "${ko_report}" 'bare `sfs` generated shim' "KO report bare sfs finding"
assert_contains "${ko_report}" 'generated `sfs.cmd` shim' "KO report generated sfs.cmd finding"
assert_contains "${ko_report}" 'positional fallback' "KO report hardened shim positional fallback"
assert_contains "${ko_report}" 'deterministic wrapper' "KO report deterministic shim fix"
assert_contains "${ko_report}" 'scoop update sfs' "KO report direct Scoop recovery"
assert_contains "${ko_report}" 'sfs.cmd upgrade` 자체로 self-upgrade' "KO report runtime self-upgrade smoke"
assert_contains "${ko_report}" 'sfs.cmd start --id ci-korean-sprint-test --force "스프린트 생성 테스트"' "KO report Korean CI smoke"
assert_contains "${ko_report}" "sprint 디렉터리가 비어 있는 것 자체는 버그가 아닙니다" "KO report start semantics"
assert_contains "${ko_report}" "최종 문제점 정리" "KO report final issue summary"
assert_contains "${ko_report}" "| P1 |" "KO report P1"
assert_contains "${ko_report}" "| P10 |" "KO report P10"
assert_contains "${ko_report}" "| P11 |" "KO report P11"
assert_contains "${ko_report}" "| P12 |" "KO report P12"
assert_contains "${ko_report}" "| P13 |" "KO report P13"
assert_contains "${ko_report}" "| P14 |" "KO report P14"
assert_contains "${ko_report}" "| P15 |" "KO report P15"
assert_contains "${ko_report}" "| P16 |" "KO report P16"
assert_contains "${ko_report}" "| P17 |" "KO report P17"
assert_contains "${ko_report}" "| P18 |" "KO report P18"
assert_contains "${ko_report}" "| P19 |" "KO report P19"
assert_contains "${ko_report}" "| P20 |" "KO report P20"
assert_contains "${ko_report}" "| P21 |" "KO report P21"
assert_contains "${ko_report}" "| P22 |" "KO report P22"
assert_contains "${ko_report}" "| P23 |" "KO report P23"
assert_contains "${ko_report}" "| P24 |" "KO report P24"
assert_contains "${ko_report}" 'refs/tags/v/tags/v0.6.49' "KO report broken PowerShell refspec"
assert_contains "${ko_report}" '${brokenVersion}' "KO report braced PowerShell variable"
assert_contains "${ko_report}" 'SFS_NATIVE_RAW_ARGS' "KO report raw arg fallback"
assert_contains "${ko_report}" 'SFS_NATIVE_CMDLINE' "KO report saved cmdline fallback"
assert_contains "${ko_report}" 'Win32_Process' "KO report parent cmdline fallback"
assert_contains "${ko_report}" 'Test-SfsUsableArgs([string[]] $Items)' "KO report usable args root cause"
assert_contains "${ko_report}" '$InvocationArgs' "KO report invocation args root cause"
assert_contains "${ko_report}" 'SFS_ARGTRACE_PS_SELECTED_SOURCE=env' "KO report env selected source trace"
assert_contains "${ko_report}" 'SFS_WINDOWS_ARG_TRACE=1' "KO report opt-in arg trace"
assert_contains "${ko_report}" 'SFS_ARGTRACE_PS_FINAL_ARGS=.*version' "KO report final arg trace contract"
assert_contains "${ko_report}" 'sfs.cmd upgrade --yes' "KO report non-interactive upgrade smoke"
assert_contains "${ko_report}" 'PS_RELOAD_SCRIPT' "KO report reload script trace"
assert_contains "${ko_report}" '/dev/tty' "KO report CI tty prompt finding"
assert_contains "${ko_report}" "최종 기준선은 0.6.56" "KO report final baseline"

assert_contains "${en_report}" "fatal error - couldn't create signal pipe, Win32 error 5" "EN report Win32 error"
assert_contains "${en_report}" "sfs.cmd -> sfs.ps1 -> Bash runtime" "EN report fixed bridge"
assert_contains "${en_report}" "usage-only" "EN report usage-only"
assert_contains "${en_report}" "mojibake" "EN report mojibake"
assert_contains "${en_report}" "sfs.cmd start \"이미지 프롬프트 고도화\"" "EN report repro command"
assert_contains "${en_report}" "Homebrew installed layout" "EN report installed layout"
assert_contains "${en_report}" "TIVE_READONLY_DONE" "EN report batch replacement tail"
assert_contains "${en_report}" '`e` and `*`' "EN report short replacement tail"
assert_contains "${en_report}" 'Windows self-upgrade belongs in `sfs.ps1`' "EN report ps1 self-upgrade owner"
assert_contains "${en_report}" "same parsed line" "EN report same-line exit"
assert_contains "${en_report}" "ASCII-only" "EN report ASCII-only parser guard"
assert_contains "${en_report}" "SFS_ORIGINAL_ARGS" "EN report cached arg finding"
assert_contains "${en_report}" 'call-label `%*`' "EN report direct percent-star forwarding"
assert_contains "${en_report}" "Batch-label forwarding" "EN report batch label finding"
assert_contains "${en_report}" "call-label-dispatch-free thin PowerShell trampoline" "EN report thin cmd trampoline"
assert_contains "${en_report}" 'powershell.exe -File sfs.ps1 %*' "EN report powershell file finding"
assert_contains "${en_report}" 'SFS_NATIVE_SCRIPT @args' "EN report powershell command bridge"
assert_contains "${en_report}" 'SFS_NATIVE_ARGC' "EN report env arg count bridge"
assert_contains "${en_report}" 'SFS_NATIVE_ARG_N' "EN report numbered env arg bridge"
assert_contains "${en_report}" 'PowerShell CLI argument binding' "EN report CLI argv binding finding"
assert_contains "${en_report}" 'CMDCMDLINE' "EN report cmdcmdline fallback"
assert_contains "${en_report}" 'empty `%1..%n`' "EN report empty numbered args finding"
assert_contains "${en_report}" 'bin\sfs.ps1' "EN report Scoop ps1 shim target"
assert_contains "${en_report}" '25533332634' "EN report 0.6.45 failed smoke run"
assert_contains "${en_report}" '25534566676' "EN report 0.6.46 failed smoke run"
assert_contains "${en_report}" '25535059980' "EN report 0.6.47 failed smoke run"
assert_contains "${en_report}" '25539387684' "EN report 0.6.48 failed smoke run"
assert_contains "${en_report}" '25541086874' "EN report 0.6.49 failed smoke run"
assert_contains "${en_report}" '25542777986' "EN report 0.6.50 failed smoke run"
assert_contains "${en_report}" '25543802195' "EN report 0.6.51 failed smoke run"
assert_contains "${en_report}" '25545120029' "EN report 0.6.52 failed smoke run"
assert_contains "${en_report}" '25546859759' "EN report 0.6.53 failed smoke run"
assert_contains "${en_report}" '25548381094' "EN report 0.6.54 failed smoke run"
assert_contains "${en_report}" 'automatic `$args`' "EN report automatic args path"
assert_contains "${en_report}" 'bare `sfs` generated shim' "EN report bare sfs finding"
assert_contains "${en_report}" 'generated `sfs.cmd` shim' "EN report generated sfs.cmd finding"
assert_contains "${en_report}" 'positional fallback' "EN report hardened shim positional fallback"
assert_contains "${en_report}" 'deterministic wrappers' "EN report deterministic shim fix"
assert_contains "${en_report}" 'scoop update sfs' "EN report direct Scoop recovery"
assert_contains "${en_report}" 'runs `sfs.cmd upgrade` for the' "EN report runtime self-upgrade smoke"
assert_contains "${en_report}" 'sfs.cmd start --id ci-korean-sprint-test --force "스프린트 생성 테스트"' "EN report Korean CI smoke"
assert_contains "${en_report}" 'An empty sprint directory after `sfs start` is not, by itself, a bug' "EN report start semantics"
assert_contains "${en_report}" "Final Issue Summary" "EN report final issue summary"
assert_contains "${en_report}" "| P1 |" "EN report P1"
assert_contains "${en_report}" "| P10 |" "EN report P10"
assert_contains "${en_report}" "| P11 |" "EN report P11"
assert_contains "${en_report}" "| P12 |" "EN report P12"
assert_contains "${en_report}" "| P13 |" "EN report P13"
assert_contains "${en_report}" "| P14 |" "EN report P14"
assert_contains "${en_report}" "| P15 |" "EN report P15"
assert_contains "${en_report}" "| P16 |" "EN report P16"
assert_contains "${en_report}" "| P17 |" "EN report P17"
assert_contains "${en_report}" "| P18 |" "EN report P18"
assert_contains "${en_report}" "| P19 |" "EN report P19"
assert_contains "${en_report}" "| P20 |" "EN report P20"
assert_contains "${en_report}" "| P21 |" "EN report P21"
assert_contains "${en_report}" "| P22 |" "EN report P22"
assert_contains "${en_report}" "| P23 |" "EN report P23"
assert_contains "${en_report}" "| P24 |" "EN report P24"
assert_contains "${en_report}" 'refs/tags/v/tags/v0.6.49' "EN report broken PowerShell refspec"
assert_contains "${en_report}" '${brokenVersion}' "EN report braced PowerShell variable"
assert_contains "${en_report}" 'SFS_NATIVE_RAW_ARGS' "EN report raw arg fallback"
assert_contains "${en_report}" 'SFS_NATIVE_CMDLINE' "EN report saved cmdline fallback"
assert_contains "${en_report}" 'Win32_Process' "EN report parent cmdline fallback"
assert_contains "${en_report}" 'Test-SfsUsableArgs([string[]] $Items)' "EN report usable args root cause"
assert_contains "${en_report}" '$InvocationArgs' "EN report invocation args root cause"
assert_contains "${en_report}" 'SFS_ARGTRACE_PS_SELECTED_SOURCE=env' "EN report env selected source trace"
assert_contains "${en_report}" 'SFS_WINDOWS_ARG_TRACE=1' "EN report opt-in arg trace"
assert_contains "${en_report}" 'SFS_ARGTRACE_PS_FINAL_ARGS=.*version' "EN report final arg trace contract"
assert_contains "${en_report}" 'sfs.cmd upgrade --yes' "EN report non-interactive upgrade smoke"
assert_contains "${en_report}" 'PS_RELOAD_SCRIPT' "EN report reload script trace"
assert_contains "${en_report}" '/dev/tty' "EN report CI tty prompt finding"
assert_contains "${en_report}" "The final baseline is 0.6.56" "EN report final baseline"

assert_contains "${DIST_DIR}/docs/ko/index.md" "windows-wrapper-incident-0.6.56.md" "KO index report link"
assert_contains "${DIST_DIR}/docs/en/index.md" "windows-wrapper-incident-0.6.56.md" "EN index report link"
assert_contains "${DIST_DIR}/docs/ko/current-product-shape.md" "Windows 래퍼 안정화" "KO product shape wrapper section"
assert_contains "${DIST_DIR}/docs/en/current-product-shape.md" "Windows Wrapper Stabilization" "EN product shape wrapper section"
assert_contains "${DIST_DIR}/GUIDE.md" "Windows SFS 래퍼 장애 요약 보고서" "GUIDE report link"
assert_contains "${DIST_DIR}/docs/en/guide.md" "Windows SFS wrapper incident report" "EN guide report link"
assert_contains "${release_notes}" "Windows SFS 래퍼 장애 요약 보고서" "release notes report link"
assert_contains "${release_notes}" "스프린트 생성 테스트" "release notes Korean Windows smoke"
assert_contains "${changelog}" "Windows wrapper incident reports" "CHANGELOG report entry"
assert_contains "${changelog}" "ci-korean-sprint-test" "CHANGELOG Korean Windows smoke"

echo "test-windows-wrapper-incident-report: OK"
